server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: queuebot
    static_configs:
      - targets:
          - localhost
        labels:
          job: queuebot
          __path__: /var/log/queuebot/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            chat_title: chat_title
            queue: queue
            actor: actor
      - labels:
          chat_title:
          queue:
          actor:
          level: level
          message: message



